services:
  - type: web
    name: cm-calculator
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: HOST
        value: 0.0.0.0
